import fs from "fs";
import path from "path";
import { task } from "hardhat/config";

function repoPath(...parts: string[]) {
  return path.join(__dirname, "..", ...parts);
}

task("sync-ui", "Sync UI contract address/ABI from deployments/sepolia")
  .addOptionalParam("deploymentsNetwork", "Deployment network folder under deployments/", "sepolia")
  .setAction(async (args, _hre) => {
    const deploymentsNetwork = String(args.deploymentsNetwork);
    const deploymentFile = repoPath("deployments", deploymentsNetwork, "ShroudNet.json");
    const outFile = repoPath("ui", "src", "config", "contracts.ts");

    if (!fs.existsSync(deploymentFile)) {
      throw new Error(`Missing deployment file: ${deploymentFile}`);
    }

    const deployment = JSON.parse(fs.readFileSync(deploymentFile, "utf8")) as { address: string; abi: unknown };

    const content = `// Auto-generated by "npx hardhat sync-ui --deployments-network ${deploymentsNetwork}"
// Do not edit manually.

export const CONTRACT_ADDRESS = '${deployment.address}';

export const CONTRACT_ABI = ${JSON.stringify(deployment.abi, null, 2)} as const;
`;

    fs.writeFileSync(outFile, content, "utf8");
    console.log(`Wrote ${outFile}`);
  });
